FirstPythonProject/mysite/devomag/urls.py
from django.conf.urls import url
from devomag import views

urlpatterns = [
	#index view at /devomag/
	url(r'^$', views.IndexView.as_view(), name='index'),
	#VIEW FOR THANKYOU AFTER SUBMISSION
	url(r'^submit-new-article/thanks/$', views.thankyou, name='thankyou'),
	#detail view at /devomag/*BLOG-ENTRY*/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	#detail view for author at/devomag/author/*ID*
	url(r'^(?P<pk>[0-9]+)/author/$', views.AuthDetailsView.as_view(), name='auth_details'),
	#url for new article submission
	url(r'^submit-new-article/$', views.NewArticle, name='newarticle')
	]
#views.NOMEDELLATUAVISTA!!, that is the same in name parameter

FirstPythonProject/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # assigning this url to a namespace	
    url(r'^polls/', include('polls.urls', namespace="polls")),
    #assigning this url to the devomag namespace
    url(r'^devomag/', include('devomag.urls', namespace="devomag"))
)

FirstPythonProject/mysite/polls/urls.py
from django.conf.urls import url
from polls import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	# ex: /polls/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	# ex: /polls/5/results/
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	# ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

FirstPythonProject/mysite/devomag/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
	auth_name = models.CharField(max_length=100)
	auth_nationality = models.CharField(max_length=100)
	auth_age = models.IntegerField()
	#THIS LETS YOU SEE PROPERLY THE OBJECT WHEN ADMINISTRATING. IT ALSO FIXES THE LIST POINTING TO OBJECTS IN FORM FROM MODELS
	def __unicode__(self):
       		return self.auth_name

class BlogEntry(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	pub_date = models.DateTimeField('date_published')
	author = models.ForeignKey(Author)
	
	def __unicode__(self):
       		return self.title

FirstPythonProject/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date_published')
	
	def __unicode__(self):
		return self.question_text
	
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now



class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __unicode__(self):
		return self.choice_text

FirstPythonProject/mysite/devomag/views.py
import datetime

from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import generic
from django.utils import timezone
from django.forms import ModelForm

from devomag.models import Author, BlogEntry

# Create your views here.

class IndexView(generic.ListView):
	template_name = 'devomag/index.html'
	#*** ATTENTION *** the name variable context_object_name is mandatory to talk with the INDEX.HTML!!
	context_object_name = 'blog_entries_list'

	def get_queryset(self):
		#First step: return all objects ...OK
		#Second step: return object not older than a week from now()
		time_span = timezone.now()
		time_span = time_span - datetime.timedelta(days=7) 
		return BlogEntry.objects.filter(pub_date__gte=time_span)

class DetailView(generic.DetailView):
	template_name = 'devomag/detail.html'
	model = BlogEntry
    
	def get_queryset(self):
		time_span = timezone.now()
		time_span = time_span - datetime.timedelta(days=7)
		"""
		try:
			obj = get_object_or_404(BlogEntry, self.kwargs['id'])
		except BlogEntry.DoesNotExist:
			raise Http404
		"""	
		obj = BlogEntry.objects.filter(pub_date__gte=time_span)
		if not obj:
			raise Http404
		else:	 
			return obj

class AuthDetailsView(generic.DetailView):
	template_name = 'devomag/auth_details.html'
	model = Author

	def get_queryset(self):

		return Author.objects.all()

class ArticleForm(ModelForm):
	class Meta:
		model = BlogEntry
		#i will use all fields ad mandatory

def NewArticle(request):
	if request.method == 'POST':
		"""
		After the form is submitted i clear the parameters and save it, redirecting to the thank you page.
		I will not do validation here becasue it is done client side with AJAX.
		"""	
		f =  ArticleForm(request.POST)
		if f.is_valid():
			f.save()
			return HttpResponseRedirect('/devomag/submit-new-article/thanks/')
		return render(request, 'devomag/newarticle.html', {'entry_form' : f })
	else:
		entry_form = ArticleForm()
		return render(request, 'devomag/newarticle.html', {'entry_form' : entry_form })

def thankyou(request):
	return render(request, 'devomag/thankyou.html')

FirstPythonProject/mysite/polls/views.py
from django.shortcuts import get_object_or_404 , render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

#from django.template import RequestContext, loader

from polls.models import Question, Choice



# Standard view 
#def index(request):
#	return HttpResponse("Hello, World. You're at the polls index.")

# View with a collection of the latest 5 question available

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""Return the last five published questions. (not including those set to be published in the future.)"""
		# __LTE after field name means: LESS THAN or EQUAL
		# __GTE means GREATER THAN or EQUAL

		return Question.objects.filter(
		pub_date__lte=timezone.now(),
		).exclude( 
		    #Exlcude test if the question has choices through the foreign key and remove question with no answers. 
			choice__question__isnull=True
			).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
		Exclude any questions that aren't published yet
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	p = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question' : p, 
			'error_message' : "You didn't select a choice!",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		#Always return a ResponseRedirect after succesfully dealing
		# with POST. It prevents data being posted twice if a user hits the back button.
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

FirstPythonProject/mysite/devomag/templates/devomag/auth_details.html
<h2>More about the Author</h2>
<p>{{ author.auth_name }}</p>
<p>{{ author.auth_nationality }}</p>
<p>{{ author.auth_age }}</p>

FirstPythonProject/mysite/devomag/templates/devomag/detail.html
<h2>{{ blogentry.title }}</h2>
<a href="{% url 'devomag:auth_details' blogentry.author.id %}" id="name_author">{{ blogentry.author.auth_name}}</a>
<h3>{{ blogentry.pub_date }}</h3>
<p>
	{{ blogentry.content }}
</p>

<a href="{% url 'devomag:index' %}">Go back to Blog</a>

FirstPythonProject/mysite/devomag/templates/devomag/index.html
<h1>Blog Entries</h1>

{% if blog_entries_list %}
<ul>
	{% for blogentry in blog_entries_list %}
	<li><a href="{% url 'devomag:detail' blogentry.id %}">{{ blogentry.title }}</a></li>
	{% endfor %}
</ul>
{% else %}
<p>No Entries Found</p>
{% endif %}


<a href="{% url 'devomag:newarticle' %}">Submit a new article</a>

FirstPythonProject/mysite/devomag/templates/devomag/newarticle.html
<h2>Create and submit a new article.</h2>
<form action="{% url 'devomag:newarticle' %}" method="post" id="new_article_form">
{% csrf_token %}	
{% for field in entry_form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}
<input type="submit" value="Submit"/>
</form>
<a href="{% url 'devomag:index' %}">Cancel submission and go back</a>

FirstPythonProject/mysite/devomag/templates/devomag/thankyou.html
thank you!!

<a href="{% url 'devomag:index' %}">Go to HomePage</a>

FirstPythonProject/mysite/polls/templates/polls/detail.html
{% load staticfiles %}
{% load polls_extra %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1> {{ question.question_text }}</h1>
<h2>TEST NEW FILTER, {{ "THIS IS BIG IN THE TEMPLATE"|lower }}  AND {{ "this is small"|upper }} and this has x letters in it: {{ "xxzyzkshzkxxhskwxx"|cut:"x" }}</h2>


<p>
{% upper %}
this text is lower case in between a custom tag that converst it automatically.
{% endupper %}
</p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
<a href="{% url 'polls:index' %}">Go Back</a>

FirstPythonProject/mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No Polls are available.</p>
{% endif %}


<a href="/admin">Go to Site Administration</a>

FirstPythonProject/mysite/polls/templates/polls/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>